[package]
name = "cyd-encoder"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "encoder"
path = "./src/encoder.rs"

[[bin]]
name = "player"
path = "./src/player.rs"

[dependencies]
cyd-format = { path = "../cyd-format" }
argh = "0.1.13"
